repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      # - id: pretty-format-json
      #   args: ['--autofix']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: forbid-new-submodules
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==23.1.0]
      - id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==3.3.1]
      - id: nbqa
        entry: nbqa autoflake -i
        name: nbqa-autoflake
        alias: nbqa-autoflake
        additional_dependencies: [autoflake==2.2.0]
      - id: nbqa-flake8
        additional_dependencies: [flake8==6.0.0]
      - id: nbqa-mypy
        additional_dependencies: [mypy==1.3.0]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
