[tool.poetry]
name = "discharge-summaries"
version = "0.1.0"
description = ""
authors = ["simonEllershaw <simje@live.co.uk>"]
readme = "README.md"
packages = [{include = "discharge_summaries"}]

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"
pandas = "^2.0.2"
scikit-learn = "^1.2.2"
tiktoken = "^0.4.0"
pydantic = "^1.10.8"
langchain = "^0.0.192"
mypy = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]

[[tool.mypy.overrides]]
module = "pydantic"
ignore_missing_imports = true
