[tool.poetry]
name = "discharge-summaries"
version = "0.1.0"
description = ""
authors = ["simonEllershaw <simje@live.co.uk>"]
readme = "README.md"
packages = [{include = "discharge_summaries"}]

[tool.poetry.dependencies]
python = "^3.10"
medcat = "^1.7.0"
jupyter = "^1.0.0"
pandas = "^2.0.2"
mypy = "^1.4.0"
python-dotenv = "^1.0.0"
openai = "^0.27.8"
rich = "^13.4.2"
pydantic = "^1.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autoflake]
remove_all_unused_imports = true

[tool.black]
preview = true

[tool.isort]
profile = "black"
filter_files = true

[tool.mypy]

[[tool.mypy.overrides]]
module = ["pydantic", "pandas", "sklearn.*", "tiktoken", "rich", "tqdm.*", "spacy", "medcat.*", "numpy", "dotenv"]
ignore_missing_imports = true
